Laboratory work #1, Zaytseva Vita  - 20FPL2
fipl-hse/2021-2-level-ctlr pull request #14
Opened 2022-03-09 11:19 UTC by vitazaytseva

2022-03-09 16:23 UTC, demid5111 requested changes
great start!

2022-03-09 16:23 UTC, demid5111 commented on seminars/03.04.2022/index.html
> +<!DOCTYPE html>
you cannot commit unrelated files. discard

2022-03-09 16:23 UTC, demid5111 commented on seminars/03.04.2022/index.html
> +  <head>
the same for logo

2022-03-09 16:23 UTC, demid5111 commented on seminars/03.04.2022/try_requests.py
> -if __name__ == '__main__':
you cannot commit changes to the seminars listings. instead move the code to the place it is expected


carefully read the docs. first part of assignment should be made within `scrapper.py` module.

2022-03-09 16:23 UTC, demid5111 commented on seminars/03.04.2022/try_requests.py
> +# if __name__ == '__main__':
especially we never commit commented code, maybe rarely and only by mistake. please discard

2022-03-16 13:43 UTC, demid5111 requested changes
it is time to start. there is plenty of things to do

2022-03-16 13:43 UTC, demid5111 commented on requirements.txt
> +requests
better to specify particular versions

2022-03-16 13:43 UTC, demid5111 commented on scrapper.py
>      pass
remove unnecessary stubs

2022-03-16 13:43 UTC, demid5111 commented on scrapper.py
> +    response = requests.get('https://russkayarech.ru/ru')
I see that you are able to download a page. But this is far not enough to hand over programming assignment

2022-03-23 13:21 UTC, demid5111 commented
you are at risk of missing a deadline! hurry up!

2022-03-30 13:50 UTC, demid5111 requested changes
I have not seen the tests being run. Have you looked into the problem or asked at the forum? without tests results you will not be accepted for oral hand over

2022-03-30 13:50 UTC, demid5111 commented on scrapper.py
> +            if len(self.urls) >= 100:
number of articles to collect should be controlled by a configuration file

2022-03-30 13:50 UTC, demid5111 commented on scrapper.py
> +        pdf_without_lit = pdf_with_lit.split('Литература')[0]
why do we need an intermediate variable?

2022-03-30 13:50 UTC, demid5111 commented on scrapper.py
> +    path_to_base_path = Path(base_path)
are there cases when `base_path` is not a Path instance?

2022-03-30 13:50 UTC, demid5111 commented on scrapper.py
> +    seed_urls = configuration["seed_urls"]
is it guaranteed to have `seed_urls `and `total_articles_to_find_and_parse` in a configuration file?

2022-03-30 13:50 UTC, demid5111 commented on scrapper.py
> +    for main_article_url in crawler.urls:
is there a way to get the index of the current element without creating a counter outside the loop?

2022-04-07 11:52 UTC, demid5111 requested changes
nice progress!

2022-04-07 11:52 UTC, demid5111 commented on scrapper.py
>          pass
it is not implemented

2022-04-07 11:52 UTC, demid5111 commented on scrapper.py
> +        article = article_parser.parse()
parse method also makes requests to the website, we need to make a request human-like as well (as you did in crawler)

2022-04-07 11:52 UTC, demid5111 commented on scrapper.py
> +        self.article.date = datetime.date(int(year), 1, 1)
month should be retrieved from an issue number

2022-04-07 15:53 UTC, vitazaytseva commented on scrapper.py
> +    if 'seed_urls' not in configuration:
Because here before checking for the existence of a key, we check for seed urls under that key. I've realized my mistake, redo

2022-04-08 12:05 UTC, demid5111 requested changes
task: print length of literature, number of pages of PDF file

2022-04-14 13:45 UTC, demid5111 requested changes
still several comments about scrapper and no progress with a pipeline!

2022-04-14 13:45 UTC, demid5111 commented on scrapper.py
>          pass
still applies

2022-04-22 16:46 UTC, demid5111 requested changes
still expecting implementation for a higher score. I believe in you

2022-04-22 16:46 UTC, demid5111 commented on config/target_score.txt
> +6
you should target 10! this is absolutely doable for a student like you

2022-04-22 16:46 UTC, demid5111 commented on pipeline.py
> +            pattern = re.search(r'\d+', file.name)
exactly what I was talking about today: pattern in a loop

2022-04-22 16:46 UTC, demid5111 commented on pipeline.py
> +            if pattern:
make code less nested

2022-04-22 16:46 UTC, demid5111 commented on pipeline.py
> +            print(*cleaned_tokens)
rm

2022-04-22 16:46 UTC, demid5111 commented on pipeline.py
> +            article.save_as(*cleaned_tokens, kind=ArtifactType.cleaned)
why do you unpack list here?

2022-04-22 16:46 UTC, demid5111 commented on pipeline.py
> +            article.save_as(*cleaned_tokens, kind=ArtifactType.cleaned)
save_as accepts a string, are you passing here a string?

2022-04-22 16:46 UTC, demid5111 commented on pipeline.py
> +        name_pattern = re.match(r'\d+_(raw.txt)', file.name)
why do you make a group from raw.txt?

2022-04-22 16:46 UTC, demid5111 commented on requirements.txt
> +pymystem3==0.2.0
order?

2022-04-22 16:46 UTC, demid5111 commented on pipeline.py
> +        name_pattern = re.match(r'\d+_(raw.txt)', file.name)
you could already extract ID instead of creating several patterns, and even worse - in a loop

2022-04-22 16:46 UTC, demid5111 commented on pipeline.py
> +            morphological_token = MorphologicalToken(original_word=analyzed_word.get('text'))
all pieces are very fragile - you might have empty dictionaries and what happens then?

2022-04-22 16:46 UTC, demid5111 commented on pipeline.py
> +            morphological_token = MorphologicalToken(original_word=analyzed_word.get('text'))
or analysis lists might be empty

2022-04-22 16:47 UTC, demid5111 commented on pipeline.py
> +from pathlib import Path
and, finally, order of imports

2022-04-27 13:28 UTC, demid5111 requested changes
keep going, only one day is left. make sure you address all the comments and pipeline is green by Friday

2022-05-03 10:12 UTC, closed without merging