Laboratory Work #1, Anastasia Buntova - 20FPL1
fipl-hse/2021-2-level-ctlr pull request #24
Opened 2022-03-09 20:24 UTC by DangerousCrocodile

2022-03-10 11:34 UTC, demid5111 requested changes

2022-03-10 11:34 UTC, demid5111 commented on pipeline.py
> +import requests
you should include it in the requirements file, better with a version

2022-03-16 15:19 UTC, demid5111 requested changes
continue to HTMLParser implementation

2022-03-16 15:19 UTC, demid5111 commented on requirements.txt
> +requests>=2.27.1
1. alphabetic order
2. no testing dependencies in requirements.txt. Instead, they should be in requirements_qa.txt
3. better to freeze exact versions (not mandatory)

2022-03-16 15:19 UTC, demid5111 commented on scrapper.py
> +import json
all imports should be grouped into:

1. standard Python imports
2. 3rd party imports
3. project imports

all imports should be in alphabetic order

2022-03-16 15:19 UTC, demid5111 commented on scrapper.py
> +# from constants import CRAWLER_CONFIG_PATH, ASSETS_PATH
we do not accept commented code. remove or uncomment

2022-03-16 15:19 UTC, demid5111 commented on scrapper.py
> +        headers = {
is there a better way to handle those configuration items? especially given they are used several times

2022-03-16 15:19 UTC, demid5111 commented on scrapper.py
> +            time.sleep(3)
🏆

2022-03-16 15:19 UTC, demid5111 commented on scrapper.py
> +                print("Something went wrong...")
it is a weak check. probably we do not want to process such an URL then? what do you think?

2022-03-16 15:19 UTC, demid5111 commented on scrapper.py
> +            soup = BeautifulSoup(response.text, "lxml")
haven't seen that in requirements

2022-03-16 15:19 UTC, demid5111 commented on scrapper.py
> +            main_block_bs = soup.find('div', {'class': 'cat-children'})
move extraction logic to the 

```python
 def _extract_url(self, article_bs):
        pass
```

2022-03-16 15:19 UTC, demid5111 commented on scrapper.py
> +                self.urls.append('https://l.jvolsu.com/' + link.get('href'))
this constant should be also moved to some configurable place

2022-03-16 15:19 UTC, demid5111 commented on scrapper.py
> +        os.rmdir(base_path)
will work for empty dictionaries only. read the docs: https://docs.python.org/3/library/os.html#os.rmdir

2022-03-16 15:19 UTC, demid5111 commented on scrapper.py
> +        os.mkdir(base_path)
might not work as well

2022-03-16 15:19 UTC, demid5111 commented on scrapper.py
> +    seed_urls = config["seed_urls"]
could it be that those keys are not in the file?

2022-03-16 15:19 UTC, demid5111 commented on scrapper.py
> +            raise IncorrectURLError
would you accept such links? https://github.com/fipl-hse/2021-2-level-ctlr/pull/24/files

should you?

2022-03-16 15:22 UTC, demid5111 commented on pipeline.py
>  """
discard changes in this file(!)

2022-03-23 14:29 UTC, demid5111 commented
Almost no progress since last time! hurry up, you are at risk of missing the first deadline!

2022-03-30 14:16 UTC, demid5111 commented
you have missed the deadline. first, make sure you finish scrapper with minimal penalty and start working on text processing pipeline, deadline will approach shortly

2022-04-07 12:06 UTC, demid5111 requested changes
apply several comments and we will talk tomorrow

2022-04-07 12:06 UTC, demid5111 commented on scrapper.py
> +        self.article.title = title[::-1][1:-2]
I do not understand the logic of taking the title. Please explain and simplify implementation

2022-04-07 12:06 UTC, demid5111 commented on scrapper_config.json
> +        "https://l.jvolsu.com/index.php/ru/archive-ru/701-science-journal-of-volsu-linguistics-2021-vol-20-no-4",
make formatting great again

2022-04-07 14:59 UTC, DangerousCrocodile commented on scrapper.py
> +            self.article.author = author.split(",")[0][4:]
Well if I remove this slice there will be smth like "\t\s\s" in the beginning of the string

2022-04-07 15:29 UTC, DangerousCrocodile commented on scrapper.py
> +        self.article.title = title[::-1][1:-2]
Now I changed it but the logic is that there's the title and the author (or authors) in the same string and I need to divide them so I search for the dot which is followed with capitalized letter (in the reversed string) so this dot will be the separator (there are some articles where a dot is placed in its title so the condition that the next letter must be capitalized is important)

2022-04-07 15:31 UTC, DangerousCrocodile commented on scrapper.py
> +        self.article.title = title[::-1][1:-2]
like in "Новак М.О. Названия музыкальных инструментов в древнерусских паримейниках XII–XIV вв. (на материале исторического корпуса «Манускрипт»)"

2022-04-07 17:56 UTC, DangerousCrocodile commented on scrapper_config.json
> +    "total_articles_to_find_and_parse": 17
Yes, I can collect it on my computer

2022-04-08 08:44 UTC, demid5111 commented on scrapper.py
> +        time.sleep(random.randint(1, 3))
this should be implemented in a logic outside the parse method - somewhere where you call it

2022-04-08 09:04 UTC, demid5111 requested changes
address the comments!

2022-04-14 14:00 UTC, demid5111 commented
no progress with a pipeline, hurry up!

2022-04-22 17:07 UTC, demid5111 requested changes
where is pipeline implementation? it is time to start

2022-04-27 15:00 UTC, demid5111 requested changes
where is pipeline implementation? are you going to show it? time is approaching

2022-04-29 08:45 UTC, demid5111 requested changes

2022-04-29 08:45 UTC, demid5111 commented on pipeline.py
> +        self.path = Path(path_to_raw_txt_data)
.

2022-04-29 08:45 UTC, demid5111 commented on pipeline.py
> +        files = self.path.glob("*")
.intermediate variable

2022-04-29 08:45 UTC, demid5111 commented on pipeline.py
> +            if "_raw.txt" in texts.name:
make it shallow

2022-04-29 08:45 UTC, demid5111 commented on pipeline.py
> +                article_id = int(pattern.search(texts.name).group(0))
number is not guaranteed

2022-04-29 08:45 UTC, demid5111 commented on pipeline.py
> +        pattern = re.compile(r'[0-9]+')
using shorhand?

2022-04-29 08:45 UTC, demid5111 commented on pipeline.py
> +        self._scan_dataset()
scanning should be made somewhere else - read docs

2022-04-29 08:45 UTC, demid5111 commented on pipeline.py
> +        articles = self.corpus_manager.get_articles()
.

2022-04-29 08:45 UTC, demid5111 commented on pipeline.py
> +            article_text = article.get_raw_text()
.

2022-04-29 08:45 UTC, demid5111 commented on pipeline.py
> +            if not token.get("analysis"):
order of checks

2022-04-29 08:45 UTC, demid5111 commented on pipeline.py
> +            morph_token.normalized_form = token['analysis'][0]['lex']
too many assumptions

2022-04-29 08:45 UTC, demid5111 commented on pipeline.py
> +            morph_token.tags_pymorphy = morphs.parse(token['text'])[0].tag
no checks (!)

2022-04-29 08:45 UTC, demid5111 commented on pipeline.py
> +    pattern = re.compile(r'[0-9]+')
.

2022-04-29 08:45 UTC, demid5111 commented on pipeline.py
> +        if "_raw.txt" in file.name:
nested

2022-04-29 08:45 UTC, demid5111 commented on pipeline.py
> +    for file in sorted(list(path_to_validate.glob('*')), key=lambda x: int(pattern.search(x.name).group(0))):
too reckless

2022-04-29 08:45 UTC, demid5111 commented on pipeline.py
> +            with open(file, 'r', encoding='utf-8') as text_file:
should be a better way to understand whether a file is empty. ask colleagues if you get stuck

2022-04-29 08:45 UTC, demid5111 commented on pipeline.py
> +            if file_id == 0 or file_id - number_of_texts > 1 or \
check that ids start from 1

2022-04-29 08:45 UTC, demid5111 commented on pos_frequency_pipeline.py
> +        articles = self.corpus_manager.get_articles()
.

2022-04-29 12:37 UTC, demid5111 requested changes

2022-04-29 12:37 UTC, demid5111 commented on pipeline.py
> +    raw_texts = sorted(list(path_to_validate.glob('*_raw.txt')), key=lambda x: int(pattern.search(x.name).group(0)))
numbers can be absent (!)

2022-05-03 10:12 UTC, closed without merging